### PR TITLE
context id

### PR DESCRIPTION
**Pull request by h4r5h4**

### CODE REVIEW

**Comment by marcusschiesser** [comment]
@h4r5h4 what was your change about?

**Comment by h4r5h4** [comment]
hi @marcusschiesser I created the PR to origin by mistake instead of my own fork. To answer your question, existing app uses a single primary knowledge base for all queries. This changes allow you to specify the scope for the knowledge base(user id, chat id). Files/embeddings will be stored under that context id and only they will be used during retrieval.

**Comment by marcusschiesser** [comment]
@h4r5h4 That's actually a good idea. We want to add multiple knowledge bases soon and once we have this, different users might might need access to different knowledge bases

**Comment by marcusschiesser** [comment]
@h4r5h4 this might be interesting for you: RAGapp now supports multiple RAGapps, each one of them with their own knowledge base: https://github.com/ragapp/ragapp/tree/main/deployments/multiple-ragapps

**Comment by h4r5h4** [comment]
thanks for the heads up @marcusschiesser 
my fork is currently too far behind 😅 
will sync and give it a try.

**Pull request closed without merging**
