### PR TITLE
I would like to add the Groq API

### PR DESCRIPTION
**Pull request by Jac-Zac**
I think it would be nice to be able to use the groq api since it has a free tier and is extremely fast. I'm not very familiar with the framework, thus I had a bit of problems setting up things so that create_llama works as expected. But as I first step I tough this might be useful. Then I suppose we have to change the settings.py to add something like this: 

```python
def init_settings():
    model_provider = os.getenv("MODEL_PROVIDER")
    match model_provider:
        case "openai":
            init_openai()
        case "groq":
            init_groq()
        case "ollama":
            init_ollama()
        case "anthropic":
            init_anthropic()
        case "gemini":
            init_gemini()
        case "azure-openai":
            init_azure_openai()
        case _:
            raise ValueError(f"Invalid model provider: {model_provider}")
    Settings.chunk_size = int(os.getenv("CHUNK_SIZE", "1024"))
    Settings.chunk_overlap = int(os.getenv("CHUNK_OVERLAP", "20"))
```

```python
def init_groq():
    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
    from llama_index.llms.groq import Groq

    model_map: Dict[str, str] = {
        "llama3-8b": "llama3-8b-8192",
        "llama3-70b": "llama3-70b-8192",
        "mixtral-8x7b": "mixtral-8x7b-32768",
    }

    embed_model_map: Dict[str, str] = {
        "all-MiniLM-L6-v2": "sentence-transformers/all-MiniLM-L6-v2",
        "all-mpnet-base-v2": "sentence-transformers/all-mpnet-base-v2",
    }

    Settings.llm = Groq(model=model_map[os.getenv("MODEL")])
    Settings.embed_model = HuggingFaceEmbedding(
        model_name=embed_model_map[os.getenv("EMBEDDING_MODEL")]
    )
```

Hopefully this helps and might be interesting. Thanks for the nice work btw

### CODE REVIEW

**Comment by Jac-Zac** [comment]
Also I just notice that I didn't see that the groq api key was inside on of the file that I have committed but I have revoked it so that is not a problem

**Comment by marcusschiesser** [comment]
@Jac-Zac thanks for your change! Adding Groq is a great idea. The settings.py is copied from https://github.com/run-llama/create-llama/blob/9c9decbb88bade76f7aa086a39dbac2dfdf595e0/templates/types/streaming/fastapi/app/settings.py#L4, so you best send a PR to create-llama first - after I'll release it, we can release this PR (you'll need then update the create-llama version in the `Makefile`)

**Comment by Jac-Zac** [comment]
At this point I think we might add support for the groq api here too then

**Comment by marcusschiesser** [comment]
@Jac-Zac sure thing, can you rebase your PR to the latest main?

**Comment by Jac-Zac** [comment]
I have tried but perhaps I didn't do the rebase correctly I'm not sure it was my first time Rebasing, also I think I should add to poetry somehow the dependecy for lamaindex groq

**Comment by marcusschiesser** [comment]
@Jac-Zac no worries, we'll rebase your PR

**Comment by marcusschiesser** [comment]
@Jac-Zac thanks - i opened #77 for this

**Comment by leehuwuj** [comment]
Sorry, we must re-open this because the change in this PR: https://github.com/ragapp/ragapp/pull/77 has been rolled back. 
The reason is we need to use a local embedding inference, but the current Huggingface embedding isn't working well in the docker container. We'll look into alternative solutions for this later.

**Comment by Jac-Zac** [comment]
Could we perhaps use ollama to run one of the embedding models such as nomic-embed inside the docker container ?

**Pull request closed without merging**
